investment_company/investment_company/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('mainapp.urls')),
    path('', RedirectView.as_view(url='home/', permanent=True))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

investment_company/mainapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from .views import *

urlpatterns = [
    path('', IndexPage.as_view(), name='home'),

    # Дії із користувачем
    path('register/', RegisterUser.as_view(), name="register_user"),
    path('login/', auth_views.LoginView.as_view(template_name='mainapp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='mainapp/logout.html'), name='logout'),
    path('profile/', login_required(ProfilePage.as_view()), name="profile"),

    # Дії із моделю Client
    path('clients/', ClientListView.as_view(), name="client_list"),
    path('client_update/<int:pk>/', login_required(ClientUpdate.as_view()), name="client_update"),

    # Дії із моделю Stock
    path('stocks/', StockListView.as_view(), name='stock_list'),
    path('stocks/<int:pk>/', StockDetailView.as_view(), name="stock_detail"),

    # Дії із моделю Portfolio
    path('portfolio/<int:pk>/', login_required(PortfolioDetailView.as_view()), name="portfolio_detail"),
    path('portfolio_add/', login_required(PortfolioCreateView.as_view()), name="portfolio_create"),

    #Дії із моделю Transaction
    path("transaction_create/", login_required(TransactionCreateView.as_view()), name="transaction_create"),

    # Додаткові дії
    path('upload_csv/', staff_member_required(CsvUploadFormView.as_view()), name="upload_csv"),
    path('stock-autocomplete/', login_required(StockAutocomplete.as_view()), name="stock-autocomplete"),
]

investment_company/mainapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from phonenumber_field.modelfields import PhoneNumberField
import datetime

# Create your models here.
class Client(models.Model):
    ''' Модель яка відповідає за уявлення клієнта в базі даних.\n
        Дана модель пов'язана із такими моделями:\n
            1) User (Один до Одного)\n
        Має наступних дітей:\n
            1) Portfolio (Один до Багатьох)\n
        Має наступні поля:\n
            1) name\n
            2) surname\n
            3) email\n
            4) phone_number\n
            5) account\n'''
    name = models.CharField(
        blank=False,
        help_text="Ім'я клієнта",
        max_length=50,
        )
    surname= models.CharField(
        blank=False,
        null=True,
        help_text="Прізвище клієнта",
        max_length=50,
        )
    email=models.EmailField(
        blank=False,
        unique=True,
        help_text="Електронна пошта клієнта",
        )
    phone_number= PhoneNumberField(
        blank=False,
        unique=True,
        null=True,
        help_text="Телефонний номер клієнта",
        )
    account=models.OneToOneField(
        User,
        blank=True,
        on_delete=models.CASCADE,
        )
    first_login = models.BooleanField(
        blank=False,
        default=True,
        help_text="Чи закінчив користувач реєстрацію(ввів детальну інформацію про себе)"
    )

    def __str__(self):
        return f"{self.name} {self.surname}"
    
    def Meta(self):
        ordering = ["-name"]

class Stock(models.Model):
    ''' Модель яка відповідає за уявлення Акції в базі даних.\n
        Дана модель має наступних дітей:\n
            1) Transaction (Один до Багатьох)\n
            2) StockPrice (Один до Одного)\n
        Має наступні поля:\n
            1) symbol\n
            2) company_name\n
            3) current_price\n
            4) volume\n
            5) net_change\n
            6) percent_change\n
            7) market_capitalization\n
            8) country\n
            9) ipo\n
            10) sector\n
            11) industry\n
            12) last_price_change (неможливо редагувати)\n
            '''
    symbol= models.CharField(
        blank=False,
        unique=True,
        help_text="Короткий символ акції корпорації (напр.: TSLA для Tesla)",
        max_length=10,
        )
    company_name= models.CharField(
        blank=False,
        help_text="Повна назва компанії",
        max_length=500,
        )
    current_price= models.DecimalField(
        blank=False,
        help_text="Поточна ціна акції", 
        max_digits=16, 
        decimal_places=2,
        )
    volume= models.IntegerField(
        blank=False,
        help_text="Загальна кількість акцій, які були обмінені для даної акції за день",
        )
    net_change= models.DecimalField(
        blank=True,
        null=True,
        help_text="Різниця між поточною ціною та ціною закриття попереднього дня", 
        max_digits=16, 
        decimal_places=2,
        )
    percent_change= models.DecimalField(
        blank=True,
        null=True,
        help_text="Відсоткова зміна ціни акцій або цінного паперу в порівнянні із ціною закриття попереднього дня", 
        max_digits=5, 
        decimal_places=2,
        )
    market_capitalization= models.DecimalField(
        blank=False,
        help_text="Загальна ринкова вартість всіх випущених акцій компанії", 
        max_digits=23, 
        decimal_places=2,
        )
    country= models.CharField(
        blank=False,
        help_text="Країна, в якій знаходиться або має своє головне підрозділ компанія",
        max_length=100,
        )
    ipo= models.PositiveIntegerField(
        blank=False,
        null = True,
        validators=[
            MinValueValidator(1800), 
            MaxValueValidator(datetime.datetime.now().year)],
        help_text="Рік, коли компанія вийшла на публічний ринок, випустивши свою першу публічну пропозицію акцій. Формат: YYYY.",
        )
    sector= models.CharField(
        blank=False,
        help_text="Широка категорія, яка класифікує компанії в різні групи на основі характеру їхньої діяльності", 
        max_length=100,
        )
    industry= models.CharField(
        blank=False,
        help_text="Більш конкретна класифікація, яка подальш розділяє компанії в межах сектора відповідно до їхнього конкретного напрямку діяльності чи пропозицій продуктів/послуг", 
        max_length=100,
        )
    last_price_change= models.DateTimeField(
        blank=True,
        help_text="Останній раз, коли була перевіренна ціна на одну акцію", 
        auto_now=True,
        auto_now_add=False,
        )
    
    def __str__(self):
        return self.symbol
    
    def Meta(self):
        ordering = ["-symbol"]

class StockPrice(models.Model):
    ''' Модель яка відповідає за збереження змін цін на акцію.\n
        Дана модель пов'язана із такими моделями:\n
            1) Stock (Багато до Одного)\n
        Має наступні поля:\n
            1) stock\n
            2) price\n
            3) save_date'''
    stock = models.ForeignKey(
        Stock,
        help_text="Для якої акції зберігаються ціни",
        on_delete=models.CASCADE,
        )
    price = models.DecimalField(
        blank=False,
        help_text="Ціна акції", 
        max_digits=16, 
        decimal_places=2,
        )
    save_date = models.DateTimeField(
        blank=False,
        help_text="Дата, коли данна ціна була в акції",
        auto_now = False,
        auto_now_add=False,
    )
    
    def __str__(self):
        return f"Ціни {self.stock.symbol}"
    
    def Meta(self):
        ordering = ["-stock"]

class Portfolio(models.Model):
    ''' Модель, яка відповідає за уявлення інвестиційного портфелю клієнта.\n
        Дана модель пов'язана із наступними моделями:\n
            1) Client (Багато до Одного)\n
        Дана модель має наступних дітей:\n
            1) Transaction (Один до Багатьох)\n
        Має наступні поля:\n
            1) client\n
            2) portfolio_name\n
            3) creation_date (неможливо редагувати)\n'''
    client = models.ForeignKey(
        Client, 
        help_text="Якому клієнту належить даний інвестиційний портфель", 
        on_delete=models.CASCADE,
        )
    portfolio_name = models.CharField(
        blank=False,
        help_text="Назва інвестиційного портфелю", 
        max_length=100,
        )
    creation_date = models.DateTimeField(
        blank=True,
        help_text="Дата та час, коли був створений портфель. Додається автоматично", 
        auto_now=False, 
        auto_now_add=True,
        )
    
    def __str__(self):
        return f"Портфель {self.portfolio_name}"
    
    def investment(self):
        total_investment = 0
        for transaction in self.transaction_set.all():
            if transaction.transaction_type == 'BUY':
                total_investment += transaction.price
        return round(total_investment, 2)
    
    def value(self):
        total_value = 0
        for transaction in self.transaction_set.all():
            # if transaction.transaction_type == 'BUY':
            #     total_value += transaction.current_transaction_value()
            # elif
            match transaction.transaction_type:
                case 'BUY':
                    total_value += transaction.current_transaction_value()
                case 'SELL':
                    total_value -= transaction.current_transaction_value()
        return round(total_value, 2)

    def profit(self):
        return round(self.value() - self.investment(), 2)
    
    def get_all_buy_stock_symbols(self):
        symbol_list = []
        for transaction in self.transaction_set.all():
            if transaction.transaction_type == 'BUY' and not transaction.stock.symbol in symbol_list:
                    symbol_list.append(transaction.stock.symbol)
        return symbol_list

    def get_all_buy_stock_prices(self):
        prices_dict = {}
        already_added_symbols = []
        for transaction in self.transaction_set.all():
            if transaction.transaction_type == 'BUY': 
                if not transaction.stock.symbol in already_added_symbols:
                    prices_dict[transaction.stock.symbol] = transaction.current_transaction_value()
                    already_added_symbols.append(transaction.stock.symbol)
                else:
                    prices_dict[transaction.stock.symbol] += transaction.current_transaction_value()
        return prices_dict

    def get_all_related_buy_stocks(self):
        related_stocks = []
        for transaction in self.transaction_set.all():
            if not transaction.stock in related_stocks:
                related_stocks.append(transaction.stock)
        return related_stocks

    def get_all_related_stocks_ammount(self):
        related_stocks_ammount = {}
        for transaction in self.transaction_set.all():
            if not transaction.stock.symbol in related_stocks_ammount:
                related_stocks_ammount[transaction.stock.symbol] = transaction.stock_ammount
            else:
                related_stocks_ammount[transaction.stock.symbol] += transaction.stock_ammount
        return related_stocks_ammount
    
    def Meta(self):
        ordering = ["-portfolio_name"]

class Transaction(models.Model):
    ''' Модель яка відповідає за уявлення транзакцій по додаванню чи видаленню
        акцій з інвестиційного портфелю.\n
        Дана модель пов'язана із наступними моделями:\n
            1) Portfolio (Багато до одного)\n
            2) Stock (Багато до одного)\n
        Має наступні поля:\n
            1) portfolio\n
            2) stock\n
            3) stock_ammount\n
            4) price\n
            5) transaction_type\n
            6) deal_date (неможливо редагувати)\n'''
    portfolio = models.ForeignKey(
        Portfolio, 

investment_company/mainapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from phonenumber_field.formfields import PhoneNumberField
from .models import Client, Portfolio, Transaction, Stock
from dal import autocomplete, forward

class UserRegisterForm(UserCreationForm):
    email = forms.CharField(
        required=True, 
        widget=forms.EmailInput(
            attrs={
                'class': 'validate',
                }
            )
        )
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class ClientUpdateForm(forms.ModelForm):
    name = forms.CharField(
        max_length=50, 
        label="Ім'я", 
        help_text="Ваше повне ім'я"
        )
    surname = forms.CharField(
        max_length=50, 
        label='Прізвище',
        help_text="Ваше прізвище"
        )
    email = forms.CharField(
        required=True, 
        widget=forms.EmailInput(
            attrs={
                'class': 'validate',
                }
            )
        )
    phone_number = PhoneNumberField(
        label='Номер телефону')
    class Meta:
        model = Client
        fields = ['name', 'surname', 'email', 'phone_number']

class PortfolioCreateForm(forms.ModelForm):
    class Meta:
        model = Portfolio
        fields = ['portfolio_name',]

class TransactionCreateForm(forms.ModelForm):
    portfolio = forms.ModelChoiceField(queryset=Portfolio.objects.none())
    stock = forms.ModelChoiceField(
        queryset=Stock.objects.all(),
        widget=autocomplete.ModelSelect2(
            url='stock-autocomplete',
            forward=(forward.Field('portfolio'),
                     forward.Field('transaction_type'),),
        )
    )
    transaction_type = forms.ChoiceField(choices=Transaction.TRANSACTION_TYPE)

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(TransactionCreateForm, self).__init__(*args, **kwargs)
        portfolio_qs = Portfolio.objects.filter(client=user.client)
        self.fields['portfolio'].queryset = portfolio_qs

    class Meta:
        model = Transaction
        fields = ['portfolio', 'stock', 'stock_ammount', 'transaction_type']

class UploadFileForm(forms.Form):
    file_name = forms.CharField(max_length=100, required=False)
    file = forms.FileField()

investment_company/mainapp/templates/mainapp/base_template.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        {% block additional_includes %}
		{% endblock additional_includes %}		
		{% block title %}
        	<title>This is unedited "title" block from base_template.html</title>
        {% endblock title %}
    </head>
    <body class="pb-5">
        <nav class="navbar sticky-top border-bottom navbar-expand-lg bg-body-tertiary mb-3">
            <div class="container-fluid">
            	<a class="navbar-brand" href="{% url 'home' %}">Investment Company</a>
            	<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            		<span class="navbar-toggler-icon"></span>
            	</button>
            	<div class="collapse navbar-collapse" id="navbarSupportedContent">
            		<ul class="navbar-nav me-auto mb-2 mb-lg-0">
						{% if user.is_superuser %}
							<li class="nav-item">
								<a class="nav-link" href="/admin/">Сайт Адміністратора</a>
							</li>
						{% endif %}
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
								Всі доступні посилання
							</a>
							<ul class="dropdown-menu">
								<li><a class="dropdown-item" href="{% url 'client_list'%}">Список клієнтів</a></li>
								<li><a class="dropdown-item" href="{% url 'stock_list'%}">Список Акцій</a></li>
								<li><hr class="dropdown-divider"></li>
								{% if user.is_superuser %}
									<li><a class="dropdown-item" href="{% url 'upload_csv'%}">Завантажити CSV файл з даними про акції</a></li>
								{% else %}
									<li><a class="dropdown-item disabled" href="#">Завантажити CSV файл з даними про акції</a></li>
								{% endif %}
								
							</ul>
						</li>
						<li class="nav-item dropdown">
							{% if user.is_authenticated %}
							<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
								{{user.username}}
							</a>
							<ul class="dropdown-menu">
								<li><a class="dropdown-item" href="{% url 'profile'%}">Профіль</a></li>
								<li><form class="dropdown-item" method="post" action="{% url 'logout' %}">{% csrf_token %}<button class="btn btn-danger" type="submit">Вийти з системи</button></form></li>
							</ul>
							{% else %}
							<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
								Дії з системою
							</a>
							<ul class="dropdown-menu">
								<li><a class="dropdown-item" href="{% url 'register_user'%}">Зареєструватись</a></li>
								<li><a class="dropdown-item" href="{% url 'login'%}">Увійти в систему</a></li>
							</ul>
							{% endif %}
						</li>
                	</ul>
            	</div>
            </div>
          </nav>
		{% if messages %}
			{% for message in messages %}
				<div class="alert alert-{{ message.level_tag }} alert-dismissible">
					<div>{{ message }}</div>
					<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
				</div>
			{% endfor%} 
		{% endif %}
        {% block body %}
        	<h1 class="text-center">This is unedited "body" block from base_template.html</h6>
        {% endblock body %}
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>

investment_company/mainapp/templates/mainapp/profile.html
{% extends "mainapp/base_template.html" %}

{% block additional_includes %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
{% endblock additional_includes %}

{% block title %}
    <title>Профіль {{user.username}}</title>
{% endblock title %}

{% load static %}

{% block body %}
    {% if user.client.first_login %}
    <div class="container-sm justify-content-center pt-5 text-center">
        <h2 class="display-2 text-center">Ви ще не вели обов'язкову додаткову інформацію про себе</h2>
        <div class="border-top pt-3">
                <a class="btn btn-primary" href="{% url 'client_update' user.client.pk %}">Перейти до форми</a>
        </div>
    </div>
    {% else %}
    <div class='d-flex justify-content-center'>
        <div class="container">
            <div class="row p-3">
                <div id="profilePageHeader" class="container" style="background-image: url('{% static 'mainapp/img/default_bg.jpg'%}');background-repeat: no-repeat; background-size: cover;">
                    <div class="row align-items-center">
                        <img src="https://static.vecteezy.com/system/resources/thumbnails/002/534/006/small/social-media-chatting-online-blank-profile-picture-head-and-body-icon-people-standing-icon-grey-background-free-vector.jpg" class="col-3 img-fluid">
                        <h1 class="col display-1 text-light">{{ user.username }}</h1>
                    </div>
                </div>
            </div>
            <div class="row">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item" role="presentation">
                    <button class="nav-link active" id="portfolio-tab" data-bs-toggle="tab" data-bs-target="#portfolio-tab-pane" type="button" role="tab" aria-controls="portfolio-tab-pane" aria-selected="true">Ваші інвестиційні портфелі</button>
                    </li>
                    <li class="nav-item" role="presentation">
                    <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false">Дані профіля</button>
                    </li>
                </ul>
                <div class="tab-content border" id="myTabContent">
                    <div class="tab-pane fade show active" id="portfolio-tab-pane" role="tabpanel" aria-labelledby="portfolio-tab" tabindex="0">
                        {% if user.client.portfolio_set.all %}
                            <div class="accordion p-3 m-3" id="portfolioAccordion">
                                {% for portfolio in user.client.portfolio_set.all %}
                                    <div class="accordion-item">
                                        <h2 class="accordion-header">
                                            <button class="accordion-button {% if forloop.counter != 1 %}collapsed{% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ forloop.counter }}" aria-expanded="{% if forloop.counter == 1 %}true{% else %}false{% endif %}" aria-controls="collapse{{ forloop.counter }}">
                                                {{ portfolio.portfolio_name }}
                                            </button>
                                        </h2>
                                        <div id="collapse{{ forloop.counter }}" class="accordion-collapse collapse {% if forloop.counter == 1 %}show{% endif %}" data-bs-parent="#portfolioAccordion">
                                            <div class="accordion-body">
                                                <div class="container">
                                                {% if portfolio.transaction_set.all %}
                                                    <div class="row">
                                                        <div class="col">
                                                            <p class="row"><h3 class="display-3">Вартість акцій: {{ portfolio.value }}$</h3></p>
                                                            <p class="row"><h3 class="display-3">{% if portfolio.profit < 0 %}<span class="text-danger">Збиток: {{ portfolio.profit }}$</span>{% else %}<span>Прибуток: {{ portfolio.profit }}$</span>{% endif %}</h3></p>
                                                        </div>
                                                        <div class="col-4">
                                                            <canvas id="portfolio{{forloop.counter}}Chart"></canvas>
                                                            <script>
                                                                const chart{{ forloop.counter }} = document.getElementById('portfolio{{forloop.counter}}Chart');
                                                                new Chart(chart{{ forloop.counter }}, {
                                                                    type: 'pie',
                                                                    data: {
                                                                        labels: [{% for symbol in portfolio.get_all_buy_stock_symbols %}'{{symbol}}',{% endfor %}],
                                                                        datasets: [{
                                                                            label: "Загальна вартість, $",
                                                                            data: [{% for symbol, price in portfolio.get_all_buy_stock_prices.items %}parseFloat('{{price}}'),{% endfor %}],
                                                                            hoverOffset: 4
                                                                        }]
                                                                    }
                                                                });
                                                            </script>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-1">
                                                            <a class="btn btn-primary" href="{% url 'portfolio_detail' portfolio.pk %}">Деталі</a>
                                                        </div>
                                                        <div class="col-2">
                                                            <a class="btn btn-success" href="{% url 'transaction_create' %}">Купити/Продати акції</a>
                                                        </div>
                                                    </div>
                                                {% else %}
                                                    <div class="row">
                                                        <div class="col">
                                                            З даним портфелем ще не було виконано ніяких транзакцій. Будь ласка, перейдіть за <a href="{% url 'transaction_create' %}">посиланням</a> та підтвердіть транзакції.
                                                        </div>
                                                    </div>
                                                {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="row">
                                <div class="col-4">
                                    <a class="btn btn-primary p-3 m-3" href="{% url 'portfolio_create'%}">Створити новий портфель</a>
                                </div>
                            </div>
                        {% else %}
                        <div class="text-center">
                            <a class="btn btn-link p-3 m-3" href="{% url 'portfolio_create'%}">Створити новий інвестиційний портфель</a>
                        </div>
                        {% endif %}
                    </div>
                    <div class="tab-pane fade" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">
                        {% if user.client %}
                            <div class="w-75 container p-3 m-3">
                                <div class="row">
                                    <p class="display-6 border-bottom p-3">Дані користувача</p>
                                    <div class="col">Нікнейм: {{ user.username }}</div>
                                </div>
                                <div class="row">
                                    <p class="display-6 border-bottom p-3">Дані клієнта</p>
                                    <div class="row pb-4">
                                        <div class="col">Ім'я: {{ user.client.name }}</div>
                                        <div class="col">Прізвище: {{ user.client.surname }}</div>
                                    </div>
                                    <div class="row">
                                        <div class="col">Електрона пошта: {{ user.client.email }}</div>
                                        <div class="col">Номер телефону: {{ user.client.phone_number }}</div>
                                    </div>
                                </div>
                                <div class="row">
                                    <a class="col-4 btn btn-primary mt-3" href="{% url 'client_update' user.client.pk %}">Змінити дані</a>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock body %}

investment_company/mainapp/templates/mainapp/stock_detail.html
{% extends "mainapp/base_template.html" %}

{% block title %}
    <title>Повна інформація про {{ stock.symbol }}</title>
{% endblock title %}

{% load static %}
{% block body %}
    <h1 class="has-bg-img p-5 text-light"  style="background-image: url('{% static 'mainapp/img/default_stock.jpg'%}');background-repeat: no-repeat; background-size: cover;">
        {{stock.company_name}}({{ stock.symbol }})
        {% if stock.net_change > 0 %}
            <span class="text-success">▲ +{{stock.net_change}}$(+{{stock.percent_change}}%)</span>
        {% elif stock.net_change < 0 %}
            <span class="text-danger">▼ {{stock.net_change}}$({{stock.percent_change}}%)</span>
        {% endif %}
    </h1>
    <div class="container">
        <div class="row">
            <p class="col"><b>Компанія: </b> {{ stock.company_name }}</p>
            <p class="col"><b>Країна: </b>{{ stock.country }}</p>
            <p class="col"><b>IPO: </b>{{ stock.ipo }}</p>
        </div>
        <div class="row">
            <p class="col"><b>Ціна: </b>{{ stock.current_price }}</p>
            <p class="col"><b>Зміна: </b>{{ stock.net_change }}$</p>
            <p class="col"><b>Зміна в відсотках: </b>{{ stock.percent_change }}%</p>
        </div>
        <div class="row">
            <p class="col"><b>Об'єм: </b>{{ stock.volume }}</p>
            <p class="col"><b>Капіталізація ринку: </b>{{ stock.market_capitalization }}</p>
            <p class="col"><b>Остання перевірка ціни: </b>{{ stock.last_price_change }}</p>
        </div>
        <div class="row">
            <p class="col-4"><b>Сектор: </b>{{ stock.sector }}</p>
            <p class="col-4"><b>Індустрія: </b>{{ stock.industry }}</p>
        </div>
        <div class="w-50 d-flex align-items-center justify-content-center">
            <canvas id="myChart"></canvas>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        const ctx = document.getElementById('myChart');
        const regex = new RegExp("a\.m\.|p\.m\.")
        new Chart(ctx, {
            type: 'line',
            data: {
                labels: [{% for stock_legend in stock.stockprice_set.all %}new Date('{{stock_legend.save_date}}'.replace(regex, '')).toISOString().split('T')[0],{% endfor %}],
                datasets: [{
                    label: 'Історія цін {{stock.symbol}}',
                    fill: true,
                    data: [{% for stock_legend in stock.stockprice_set.all %}parseFloat("{{stock_legend.price}}"),{% endfor %}],
                    borderWidth: 1
                }]
                },
                options: {
                scales: {
                    y: {
                    beginAtZero: true
                    }
                }
            }
        });
    </script>
{% endblock body %}